export const optionStrats = [
  { value: "Bull Call Spread", label: "Bull Call Spread" },
  { value: "Orientation", label: "Orientation" },
  { value: "Bull Put Spread", label: "Bull Put Spread" },
  { value: "Call Ratio Back Spread", label: "Call Ratio Back Spread" },
  { value: "Bear Call Ladder", label: "Bear Call Ladder" },
  { value: "Synthetic Long & Arbitrage", label: "Synthetic Long & Arbitrage" },
  { value: "Bear Put Spread", label: "Bear Put Spread" },
  { value: "Bear Call Spread", label: "Bear Call Spread" },
  { value: "Put Ratio Back spread", label: "Put Ratio Back spread" },
  { value: "The Long Straddle", label: "The Long Straddle" },
  { value: "The Short Straddle", label: "The Short Straddle" },
  { value: "The Long & Short Strangle", label: "The Long & Short Strangle" },
  { value: "Max Pain & PCR Ratio", label: "Max Pain & PCR Ratio" },
  { value: "Iron Condor", label: "Iron Condor" },
  { value: "Naked Call", label: "Naked Call" },
  { value: "Naked Put", label: "Naked Put" },
  { value: "Calendar", label: "Calendar" },
  { value: "Butterfly", label: "Butterfly" },
  { value: "Double Calendar", label: "Double Calendar" },
];
export const weekDays = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
export const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "June",
  "July",
  "Aug",
  "Sept",
  "Oct",
  "Nov",
  "Dec",
];
